// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd
{
    /// <summary>
    /// Manages [applications](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#applications) within ArgoCD.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using System.Text.Json;
    /// using Pulumi;
    /// using Argocd = Three14.Argocd;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Kustomize application
    ///     var kustomize = new Argocd.Application("kustomize", new()
    ///     {
    ///         Metadata = new Argocd.Inputs.ApplicationMetadataArgs
    ///         {
    ///             Name = "kustomize-app",
    ///             Namespace = "argocd",
    ///             Labels = 
    ///             {
    ///                 { "test", "true" },
    ///             },
    ///         },
    ///         Cascade = false,
    ///         Wait = true,
    ///         Spec = new Argocd.Inputs.ApplicationSpecArgs
    ///         {
    ///             Project = "myproject",
    ///             Destination = new Argocd.Inputs.ApplicationSpecDestinationArgs
    ///             {
    ///                 Server = "https://kubernetes.default.svc",
    ///                 Namespace = "foo",
    ///             },
    ///             Sources = new[]
    ///             {
    ///                 new Argocd.Inputs.ApplicationSpecSourceArgs
    ///                 {
    ///                     RepoUrl = "https://github.com/kubernetes-sigs/kustomize",
    ///                     Path = "examples/helloWorld",
    ///                     TargetRevision = "master",
    ///                     Kustomize = new Argocd.Inputs.ApplicationSpecSourceKustomizeArgs
    ///                     {
    ///                         NamePrefix = "foo-",
    ///                         NameSuffix = "-bar",
    ///                         Images = new[]
    ///                         {
    ///                             "hashicorp/terraform:light",
    ///                         },
    ///                         CommonLabels = 
    ///                         {
    ///                             { "this.is.a.common", "la-bel" },
    ///                             { "another.io/one", "true" },
    ///                         },
    ///                     },
    ///                 },
    ///             },
    ///             SyncPolicy = new Argocd.Inputs.ApplicationSpecSyncPolicyArgs
    ///             {
    ///                 Automated = new Argocd.Inputs.ApplicationSpecSyncPolicyAutomatedArgs
    ///                 {
    ///                     Prune = true,
    ///                     SelfHeal = true,
    ///                     AllowEmpty = true,
    ///                 },
    ///                 SyncOptions = new[]
    ///                 {
    ///                     "Validate=false",
    ///                 },
    ///                 Retry = new Argocd.Inputs.ApplicationSpecSyncPolicyRetryArgs
    ///                 {
    ///                     Limit = "5",
    ///                     Backoff = new Argocd.Inputs.ApplicationSpecSyncPolicyRetryBackoffArgs
    ///                     {
    ///                         Duration = "30s",
    ///                         MaxDuration = "2m",
    ///                         Factor = "2",
    ///                     },
    ///                 },
    ///             },
    ///             IgnoreDifferences = new[]
    ///             {
    ///                 new Argocd.Inputs.ApplicationSpecIgnoreDifferenceArgs
    ///                 {
    ///                     Group = "apps",
    ///                     Kind = "Deployment",
    ///                     JsonPointers = new[]
    ///                     {
    ///                         "/spec/replicas",
    ///                     },
    ///                 },
    ///                 new Argocd.Inputs.ApplicationSpecIgnoreDifferenceArgs
    ///                 {
    ///                     Group = "apps",
    ///                     Kind = "StatefulSet",
    ///                     Name = "someStatefulSet",
    ///                     JsonPointers = new[]
    ///                     {
    ///                         "/spec/replicas",
    ///                         "/spec/template/spec/metadata/labels/bar",
    ///                     },
    ///                     JqPathExpressions = new[]
    ///                     {
    ///                         ".spec.replicas",
    ///                         ".spec.template.spec.metadata.labels.bar",
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Helm application
    ///     var helm = new Argocd.Application("helm", new()
    ///     {
    ///         Metadata = new Argocd.Inputs.ApplicationMetadataArgs
    ///         {
    ///             Name = "helm-app",
    ///             Namespace = "argocd",
    ///             Labels = 
    ///             {
    ///                 { "test", "true" },
    ///             },
    ///         },
    ///         Spec = new Argocd.Inputs.ApplicationSpecArgs
    ///         {
    ///             Destination = new Argocd.Inputs.ApplicationSpecDestinationArgs
    ///             {
    ///                 Server = "https://kubernetes.default.svc",
    ///                 Namespace = "default",
    ///             },
    ///             Sources = new[]
    ///             {
    ///                 new Argocd.Inputs.ApplicationSpecSourceArgs
    ///                 {
    ///                     RepoUrl = "https://some.chart.repo.io",
    ///                     Chart = "mychart",
    ///                     TargetRevision = "1.2.3",
    ///                     Helm = new Argocd.Inputs.ApplicationSpecSourceHelmArgs
    ///                     {
    ///                         ReleaseName = "testing",
    ///                         Parameters = new[]
    ///                         {
    ///                             new Argocd.Inputs.ApplicationSpecSourceHelmParameterArgs
    ///                             {
    ///                                 Name = "image.tag",
    ///                                 Value = "1.2.3",
    ///                             },
    ///                             new Argocd.Inputs.ApplicationSpecSourceHelmParameterArgs
    ///                             {
    ///                                 Name = "someotherparameter",
    ///                                 Value = "true",
    ///                             },
    ///                         },
    ///                         ValueFiles = new[]
    ///                         {
    ///                             "values-test.yml",
    ///                         },
    ///                         Values = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///                         {
    ///                             ["someparameter"] = new Dictionary&lt;string, object?&gt;
    ///                             {
    ///                                 ["enabled"] = true,
    ///                                 ["someArray"] = new[]
    ///                                 {
    ///                                     "foo",
    ///                                     "bar",
    ///                                 },
    ///                             },
    ///                         }),
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Multiple Application Sources with Helm value files from external Git repository
    ///     var multipleSources = new Argocd.Application("multiple_sources", new()
    ///     {
    ///         Metadata = new Argocd.Inputs.ApplicationMetadataArgs
    ///         {
    ///             Name = "helm-app-with-external-values",
    ///             Namespace = "argocd",
    ///         },
    ///         Spec = new Argocd.Inputs.ApplicationSpecArgs
    ///         {
    ///             Project = "default",
    ///             Sources = new[]
    ///             {
    ///                 new Argocd.Inputs.ApplicationSpecSourceArgs
    ///                 {
    ///                     RepoUrl = "https://charts.helm.sh/stable",
    ///                     Chart = "wordpress",
    ///                     TargetRevision = "9.0.3",
    ///                     Helm = new Argocd.Inputs.ApplicationSpecSourceHelmArgs
    ///                     {
    ///                         ValueFiles = new[]
    ///                         {
    ///                             "$values/helm-dependency/values.yaml",
    ///                         },
    ///                     },
    ///                 },
    ///                 new Argocd.Inputs.ApplicationSpecSourceArgs
    ///                 {
    ///                     RepoUrl = "https://github.com/argoproj/argocd-example-apps.git",
    ///                     TargetRevision = "HEAD",
    ///                     Ref = "values",
    ///                 },
    ///             },
    ///             Destination = new Argocd.Inputs.ApplicationSpecDestinationArgs
    ///             {
    ///                 Server = "https://kubernetes.default.svc",
    ///                 Namespace = "default",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// ArgoCD applications can be imported using an id consisting of `{name}:{namespace}`.
    /// 
    /// ```sh
    /// $ pulumi import argocd:index/application:Application myapp myapp:argocd
    /// ```
    /// </summary>
    [ArgocdResourceType("argocd:index/application:Application")]
    public partial class Application : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether to applying cascading deletion when application is removed.
        /// </summary>
        [Output("cascade")]
        public Output<bool?> Cascade { get; private set; } = null!;

        /// <summary>
        /// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
        /// </summary>
        [Output("metadata")]
        public Output<Outputs.ApplicationMetadata> Metadata { get; private set; } = null!;

        /// <summary>
        /// The application specification.
        /// </summary>
        [Output("spec")]
        public Output<Outputs.ApplicationSpec> Spec { get; private set; } = null!;

        /// <summary>
        /// Status information for the application. **Note**: this is not guaranteed to be up to date immediately after creating/updating an application unless `wait=true`.
        /// </summary>
        [Output("statuses")]
        public Output<ImmutableArray<Outputs.ApplicationStatus>> Statuses { get; private set; } = null!;

        /// <summary>
        /// Whether to validate the application spec before creating or updating the application.
        /// </summary>
        [Output("validate")]
        public Output<bool?> Validate { get; private set; } = null!;

        /// <summary>
        /// Upon application creation or update, wait for application health/sync status to be healthy/Synced, upon application deletion, wait for application to be removed, when set to true. Wait timeouts are controlled by the provider Create, Update and Delete resource timeouts (all default to 5 minutes). **Note**: if ArgoCD decides not to sync an application (e.g. because the project to which the application belongs has a `SyncWindow` applied) then you will experience an expected timeout event if `wait = true`.
        /// </summary>
        [Output("wait")]
        public Output<bool?> Wait { get; private set; } = null!;


        /// <summary>
        /// Create a Application resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Application(string name, ApplicationArgs args, CustomResourceOptions? options = null)
            : base("argocd:index/application:Application", name, args ?? new ApplicationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Application(string name, Input<string> id, ApplicationState? state = null, CustomResourceOptions? options = null)
            : base("argocd:index/application:Application", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/Three141/pulumi-argocd/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Application resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Application Get(string name, Input<string> id, ApplicationState? state = null, CustomResourceOptions? options = null)
        {
            return new Application(name, id, state, options);
        }
    }

    public sealed class ApplicationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to applying cascading deletion when application is removed.
        /// </summary>
        [Input("cascade")]
        public Input<bool>? Cascade { get; set; }

        /// <summary>
        /// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
        /// </summary>
        [Input("metadata", required: true)]
        public Input<Inputs.ApplicationMetadataArgs> Metadata { get; set; } = null!;

        /// <summary>
        /// The application specification.
        /// </summary>
        [Input("spec", required: true)]
        public Input<Inputs.ApplicationSpecArgs> Spec { get; set; } = null!;

        /// <summary>
        /// Whether to validate the application spec before creating or updating the application.
        /// </summary>
        [Input("validate")]
        public Input<bool>? Validate { get; set; }

        /// <summary>
        /// Upon application creation or update, wait for application health/sync status to be healthy/Synced, upon application deletion, wait for application to be removed, when set to true. Wait timeouts are controlled by the provider Create, Update and Delete resource timeouts (all default to 5 minutes). **Note**: if ArgoCD decides not to sync an application (e.g. because the project to which the application belongs has a `SyncWindow` applied) then you will experience an expected timeout event if `wait = true`.
        /// </summary>
        [Input("wait")]
        public Input<bool>? Wait { get; set; }

        public ApplicationArgs()
        {
        }
        public static new ApplicationArgs Empty => new ApplicationArgs();
    }

    public sealed class ApplicationState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to applying cascading deletion when application is removed.
        /// </summary>
        [Input("cascade")]
        public Input<bool>? Cascade { get; set; }

        /// <summary>
        /// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
        /// </summary>
        [Input("metadata")]
        public Input<Inputs.ApplicationMetadataGetArgs>? Metadata { get; set; }

        /// <summary>
        /// The application specification.
        /// </summary>
        [Input("spec")]
        public Input<Inputs.ApplicationSpecGetArgs>? Spec { get; set; }

        [Input("statuses")]
        private InputList<Inputs.ApplicationStatusGetArgs>? _statuses;

        /// <summary>
        /// Status information for the application. **Note**: this is not guaranteed to be up to date immediately after creating/updating an application unless `wait=true`.
        /// </summary>
        public InputList<Inputs.ApplicationStatusGetArgs> Statuses
        {
            get => _statuses ?? (_statuses = new InputList<Inputs.ApplicationStatusGetArgs>());
            set => _statuses = value;
        }

        /// <summary>
        /// Whether to validate the application spec before creating or updating the application.
        /// </summary>
        [Input("validate")]
        public Input<bool>? Validate { get; set; }

        /// <summary>
        /// Upon application creation or update, wait for application health/sync status to be healthy/Synced, upon application deletion, wait for application to be removed, when set to true. Wait timeouts are controlled by the provider Create, Update and Delete resource timeouts (all default to 5 minutes). **Note**: if ArgoCD decides not to sync an application (e.g. because the project to which the application belongs has a `SyncWindow` applied) then you will experience an expected timeout event if `wait = true`.
        /// </summary>
        [Input("wait")]
        public Input<bool>? Wait { get; set; }

        public ApplicationState()
        {
        }
        public static new ApplicationState Empty => new ApplicationState();
    }
}
