# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'Kubernetes',
    'KubernetesExec',
]

@pulumi.output_type
class Kubernetes(dict):
    def __init__(__self__, *,
                 client_certificate: Optional[_builtins.str] = None,
                 client_key: Optional[_builtins.str] = None,
                 cluster_ca_certificate: Optional[_builtins.str] = None,
                 config_context: Optional[_builtins.str] = None,
                 config_context_auth_info: Optional[_builtins.str] = None,
                 config_context_cluster: Optional[_builtins.str] = None,
                 exec_: Optional['outputs.KubernetesExec'] = None,
                 host: Optional[_builtins.str] = None,
                 insecure: Optional[_builtins.bool] = None,
                 password: Optional[_builtins.str] = None,
                 token: Optional[_builtins.str] = None,
                 username: Optional[_builtins.str] = None):
        """
        :param _builtins.str client_certificate: PEM-encoded client certificate for TLS authentication. Can be sourced from `KUBE_CLIENT_CERT_DATA`.
        :param _builtins.str client_key: PEM-encoded client certificate key for TLS authentication. Can be sourced from `KUBE_CLIENT_KEY_DATA`.
        :param _builtins.str cluster_ca_certificate: PEM-encoded root certificates bundle for TLS authentication. Can be sourced from `KUBE_CLUSTER_CA_CERT_DATA`.
        :param _builtins.str config_context: Context to choose from the config file. Can be sourced from `KUBE_CTX`.
        :param 'KubernetesExecArgs' exec_: Configuration block to use an [exec-based credential plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins), e.g. call an external command to receive user credentials.
        :param _builtins.str host: The hostname (in form of URI) of the Kubernetes API. Can be sourced from `KUBE_HOST`.
        :param _builtins.bool insecure: Whether server should be accessed without verifying the TLS certificate. Can be sourced from `KUBE_INSECURE`.
        :param _builtins.str password: The password to use for HTTP basic authentication when accessing the Kubernetes API. Can be sourced from `KUBE_PASSWORD`.
        :param _builtins.str token: Token to authenticate an service account. Can be sourced from `KUBE_TOKEN`.
        :param _builtins.str username: The username to use for HTTP basic authentication when accessing the Kubernetes API. Can be sourced from `KUBE_USER`.
        """
        if client_certificate is not None:
            pulumi.set(__self__, "client_certificate", client_certificate)
        if client_key is not None:
            pulumi.set(__self__, "client_key", client_key)
        if cluster_ca_certificate is not None:
            pulumi.set(__self__, "cluster_ca_certificate", cluster_ca_certificate)
        if config_context is not None:
            pulumi.set(__self__, "config_context", config_context)
        if config_context_auth_info is not None:
            pulumi.set(__self__, "config_context_auth_info", config_context_auth_info)
        if config_context_cluster is not None:
            pulumi.set(__self__, "config_context_cluster", config_context_cluster)
        if exec_ is not None:
            pulumi.set(__self__, "exec_", exec_)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if insecure is not None:
            pulumi.set(__self__, "insecure", insecure)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if token is not None:
            pulumi.set(__self__, "token", token)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter(name="clientCertificate")
    def client_certificate(self) -> Optional[_builtins.str]:
        """
        PEM-encoded client certificate for TLS authentication. Can be sourced from `KUBE_CLIENT_CERT_DATA`.
        """
        return pulumi.get(self, "client_certificate")

    @_builtins.property
    @pulumi.getter(name="clientKey")
    def client_key(self) -> Optional[_builtins.str]:
        """
        PEM-encoded client certificate key for TLS authentication. Can be sourced from `KUBE_CLIENT_KEY_DATA`.
        """
        return pulumi.get(self, "client_key")

    @_builtins.property
    @pulumi.getter(name="clusterCaCertificate")
    def cluster_ca_certificate(self) -> Optional[_builtins.str]:
        """
        PEM-encoded root certificates bundle for TLS authentication. Can be sourced from `KUBE_CLUSTER_CA_CERT_DATA`.
        """
        return pulumi.get(self, "cluster_ca_certificate")

    @_builtins.property
    @pulumi.getter(name="configContext")
    def config_context(self) -> Optional[_builtins.str]:
        """
        Context to choose from the config file. Can be sourced from `KUBE_CTX`.
        """
        return pulumi.get(self, "config_context")

    @_builtins.property
    @pulumi.getter(name="configContextAuthInfo")
    def config_context_auth_info(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "config_context_auth_info")

    @_builtins.property
    @pulumi.getter(name="configContextCluster")
    def config_context_cluster(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "config_context_cluster")

    @_builtins.property
    @pulumi.getter(name="exec")
    def exec_(self) -> Optional['outputs.KubernetesExec']:
        """
        Configuration block to use an [exec-based credential plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins), e.g. call an external command to receive user credentials.
        """
        return pulumi.get(self, "exec_")

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[_builtins.str]:
        """
        The hostname (in form of URI) of the Kubernetes API. Can be sourced from `KUBE_HOST`.
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter
    def insecure(self) -> Optional[_builtins.bool]:
        """
        Whether server should be accessed without verifying the TLS certificate. Can be sourced from `KUBE_INSECURE`.
        """
        return pulumi.get(self, "insecure")

    @_builtins.property
    @pulumi.getter
    def password(self) -> Optional[_builtins.str]:
        """
        The password to use for HTTP basic authentication when accessing the Kubernetes API. Can be sourced from `KUBE_PASSWORD`.
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[_builtins.str]:
        """
        Token to authenticate an service account. Can be sourced from `KUBE_TOKEN`.
        """
        return pulumi.get(self, "token")

    @_builtins.property
    @pulumi.getter
    def username(self) -> Optional[_builtins.str]:
        """
        The username to use for HTTP basic authentication when accessing the Kubernetes API. Can be sourced from `KUBE_USER`.
        """
        return pulumi.get(self, "username")


@pulumi.output_type
class KubernetesExec(dict):
    def __init__(__self__, *,
                 api_version: _builtins.str,
                 command: _builtins.str,
                 args: Optional[Sequence[_builtins.str]] = None,
                 env: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param _builtins.str api_version: API version to use when decoding the ExecCredentials resource, e.g. `client.authentication.k8s.io/v1beta1`.
        :param _builtins.str command: Command to execute.
        :param Sequence[_builtins.str] args: Map of environment variables to set when executing the plugin.
        :param Mapping[str, _builtins.str] env: List of arguments to pass when executing the plugin.
        """
        pulumi.set(__self__, "api_version", api_version)
        pulumi.set(__self__, "command", command)
        if args is not None:
            pulumi.set(__self__, "args", args)
        if env is not None:
            pulumi.set(__self__, "env", env)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> _builtins.str:
        """
        API version to use when decoding the ExecCredentials resource, e.g. `client.authentication.k8s.io/v1beta1`.
        """
        return pulumi.get(self, "api_version")

    @_builtins.property
    @pulumi.getter
    def command(self) -> _builtins.str:
        """
        Command to execute.
        """
        return pulumi.get(self, "command")

    @_builtins.property
    @pulumi.getter
    def args(self) -> Optional[Sequence[_builtins.str]]:
        """
        Map of environment variables to set when executing the plugin.
        """
        return pulumi.get(self, "args")

    @_builtins.property
    @pulumi.getter
    def env(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        List of arguments to pass when executing the plugin.
        """
        return pulumi.get(self, "env")


