// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorPluginTemplateSpecSourceHelmFileParameter
    {
        /// <summary>
        /// Name of the Helm parameter.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Path to the file containing the values for the Helm parameter.
        /// </summary>
        public readonly string Path;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorPluginTemplateSpecSourceHelmFileParameter(
            string name,

            string path)
        {
            Name = name;
            Path = path;
        }
    }
}
