// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorMerge
    {
        /// <summary>
        /// Child generator. Generators are responsible for generating parameters, which are then combined by the parent merge generator.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGenerator> Generators;
        /// <summary>
        /// Keys to merge into resulting parameter set.
        /// </summary>
        public readonly ImmutableArray<string> MergeKeys;
        /// <summary>
        /// Generator template. Used to override the values of the spec-level template.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeTemplate? Template;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMatrixGeneratorMerge(
            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGenerator> generators,

            ImmutableArray<string> mergeKeys,

            Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeTemplate? template)
        {
            Generators = generators;
            MergeKeys = mergeKeys;
            Template = template;
        }
    }
}
