// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecIgnoreApplicationDifference
    {
        /// <summary>
        /// jq path to ignore differences
        /// </summary>
        public readonly ImmutableArray<string> JqPathExpressions;
        /// <summary>
        /// Json pointers to ignore differences
        /// </summary>
        public readonly ImmutableArray<string> JsonPointers;
        /// <summary>
        /// name
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private ApplicationSetSpecIgnoreApplicationDifference(
            ImmutableArray<string> jqPathExpressions,

            ImmutableArray<string> jsonPointers,

            string? name)
        {
            JqPathExpressions = jqPathExpressions;
            JsonPointers = jsonPointers;
            Name = name;
        }
    }
}
