// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorClusterTemplateSpecSourceHelmParameter
    {
        /// <summary>
        /// Determines whether to tell Helm to interpret booleans and numbers as strings.
        /// </summary>
        public readonly bool? ForceString;
        /// <summary>
        /// Name of the Helm parameter.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Value of the Helm parameter.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMatrixGeneratorClusterTemplateSpecSourceHelmParameter(
            bool? forceString,

            string? name,

            string? value)
        {
            ForceString = forceString;
            Name = name;
            Value = value;
        }
    }
}
