// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMergeGeneratorPullRequestBitbucketServerBasicAuth
    {
        /// <summary>
        /// Password (or personal access token) reference.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMergeGeneratorPullRequestBitbucketServerBasicAuthPasswordRef? PasswordRef;
        /// <summary>
        /// Username for Basic auth.
        /// </summary>
        public readonly string? Username;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMergeGeneratorPullRequestBitbucketServerBasicAuth(
            Outputs.ApplicationSetSpecGeneratorMergeGeneratorPullRequestBitbucketServerBasicAuthPasswordRef? passwordRef,

            string? username)
        {
            PasswordRef = passwordRef;
            Username = username;
        }
    }
}
