// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpec
    {
        /// <summary>
        /// Application set generators. Generators are responsible for generating parameters, which are then rendered into the template: fields of the ApplicationSet resource.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGenerator> Generators;
        /// <summary>
        /// Enable use of [Go Text Template](https://pkg.go.dev/text/template).
        /// </summary>
        public readonly bool? GoTemplate;
        /// <summary>
        /// Optional list of [Go Templating Options](https://pkg.go.dev/text/template#Template.Option). Only relevant if `GoTemplate` is true.
        /// </summary>
        public readonly ImmutableArray<string> GoTemplateOptions;
        /// <summary>
        /// Application Set [ignoreApplicationDifferences](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#ignore-certain-changes-to-applications).
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecIgnoreApplicationDifference> IgnoreApplicationDifferences;
        /// <summary>
        /// [Progressive Sync](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/) strategy
        /// </summary>
        public readonly Outputs.ApplicationSetSpecStrategy? Strategy;
        /// <summary>
        /// Application Set [sync policy](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/).
        /// </summary>
        public readonly Outputs.ApplicationSetSpecSyncPolicy? SyncPolicy;
        /// <summary>
        /// Application set template. The template fields of the ApplicationSet spec are used to generate Argo CD Application resources.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecTemplate Template;
        /// <summary>
        /// Application set template patch, as in the [Argo CD ApplicationSet spec](https://argocd-applicationset.readthedocs.io/en/stable/fields/#templatepatch).
        /// </summary>
        public readonly string? TemplatePatch;

        [OutputConstructor]
        private ApplicationSetSpec(
            ImmutableArray<Outputs.ApplicationSetSpecGenerator> generators,

            bool? goTemplate,

            ImmutableArray<string> goTemplateOptions,

            ImmutableArray<Outputs.ApplicationSetSpecIgnoreApplicationDifference> ignoreApplicationDifferences,

            Outputs.ApplicationSetSpecStrategy? strategy,

            Outputs.ApplicationSetSpecSyncPolicy? syncPolicy,

            Outputs.ApplicationSetSpecTemplate template,

            string? templatePatch)
        {
            Generators = generators;
            GoTemplate = goTemplate;
            GoTemplateOptions = goTemplateOptions;
            IgnoreApplicationDifferences = ignoreApplicationDifferences;
            Strategy = strategy;
            SyncPolicy = syncPolicy;
            Template = template;
            TemplatePatch = templatePatch;
        }
    }
}
