// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorListTemplateSpecSourcePluginEnv
    {
        /// <summary>
        /// Name of the environment variable.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Value of the environment variable.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMatrixGeneratorListTemplateSpecSourcePluginEnv(
            string? name,

            string? value)
        {
            Name = name;
            Value = value;
        }
    }
}
