// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPlugin
    {
        /// <summary>
        /// ConfigMap with the plugin configuration needed to retrieve the data.
        /// </summary>
        public readonly string ConfigMapRef;
        /// <summary>
        /// The input parameters used for calling the plugin.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPluginInput? Input;
        /// <summary>
        /// How often to check for changes (in seconds). Default: 3min.
        /// </summary>
        public readonly string? RequeueAfterSeconds;
        /// <summary>
        /// Generator template. Used to override the values of the spec-level template.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPluginTemplate? Template;
        /// <summary>
        /// Arbitrary string key-value pairs to pass to the template via the values field of the git generator.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Values;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPlugin(
            string configMapRef,

            Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPluginInput? input,

            string? requeueAfterSeconds,

            Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPluginTemplate? template,

            ImmutableDictionary<string, string>? values)
        {
            ConfigMapRef = configMapRef;
            Input = input;
            RequeueAfterSeconds = requeueAfterSeconds;
            Template = template;
            Values = values;
        }
    }
}
