// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorPullRequestGiteaTokenRef
    {
        /// <summary>
        /// Key containing information in Kubernetes `Secret`.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// Name of Kubernetes `Secret`.
        /// </summary>
        public readonly string SecretName;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorPullRequestGiteaTokenRef(
            string key,

            string secretName)
        {
            Key = key;
            SecretName = secretName;
        }
    }
}
