// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorPullRequestGitea
    {
        /// <summary>
        /// The Gitea API URL to talk to.
        /// </summary>
        public readonly string Api;
        /// <summary>
        /// Allow insecure tls, for self-signed certificates; default: false.
        /// </summary>
        public readonly bool? Insecure;
        /// <summary>
        /// Gitea org or user to scan.
        /// </summary>
        public readonly string Owner;
        /// <summary>
        /// Gitea repo name to scan.
        /// </summary>
        public readonly string Repo;
        /// <summary>
        /// Authentication token reference.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorPullRequestGiteaTokenRef? TokenRef;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorPullRequestGitea(
            string api,

            bool? insecure,

            string owner,

            string repo,

            Outputs.ApplicationSetSpecGeneratorPullRequestGiteaTokenRef? tokenRef)
        {
            Api = api;
            Insecure = insecure;
            Owner = owner;
            Repo = repo;
            TokenRef = tokenRef;
        }
    }
}
