// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorPluginTemplate
    {
        /// <summary>
        /// Kubernetes object metadata for templated Application.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorPluginTemplateMetadata? Metadata;
        /// <summary>
        /// The application specification.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorPluginTemplateSpec? Spec;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorPluginTemplate(
            Outputs.ApplicationSetSpecGeneratorPluginTemplateMetadata? metadata,

            Outputs.ApplicationSetSpecGeneratorPluginTemplateSpec? spec)
        {
            Metadata = metadata;
            Spec = spec;
        }
    }
}
