// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorPullRequestBitbucketServer
    {
        /// <summary>
        /// The Bitbucket REST API URL to talk to e.g. https://bitbucket.org/rest.
        /// </summary>
        public readonly string Api;
        /// <summary>
        /// Credentials for Basic auth.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorPullRequestBitbucketServerBasicAuth? BasicAuth;
        /// <summary>
        /// Project to scan.
        /// </summary>
        public readonly string Project;
        /// <summary>
        /// Repo name to scan.
        /// </summary>
        public readonly string Repo;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorPullRequestBitbucketServer(
            string api,

            Outputs.ApplicationSetSpecGeneratorPullRequestBitbucketServerBasicAuth? basicAuth,

            string project,

            string repo)
        {
            Api = api;
            BasicAuth = basicAuth;
            Project = project;
            Repo = repo;
        }
    }
}
