// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationStatusCondition
    {
        /// <summary>
        /// The time the condition was last observed.
        /// </summary>
        public readonly string? LastTransitionTime;
        /// <summary>
        /// Human-readable message indicating details about condition.
        /// </summary>
        public readonly string? Message;
        /// <summary>
        /// Application condition type.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private ApplicationStatusCondition(
            string? lastTransitionTime,

            string? message,

            string? type)
        {
            LastTransitionTime = lastTransitionTime;
            Message = message;
            Type = type;
        }
    }
}
