// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorGitFile
    {
        /// <summary>
        /// Path to the file in the repository.
        /// </summary>
        public readonly string Path;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorGitFile(string path)
        {
            Path = path;
        }
    }
}
