// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorListTemplateSpecSyncPolicyRetry
    {
        /// <summary>
        /// Controls how to backoff on subsequent retries of failed syncs.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMatrixGeneratorListTemplateSpecSyncPolicyRetryBackoff? Backoff;
        /// <summary>
        /// Maximum number of attempts for retrying a failed sync. If set to 0, no retries will be performed.
        /// </summary>
        public readonly string? Limit;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMatrixGeneratorListTemplateSpecSyncPolicyRetry(
            Outputs.ApplicationSetSpecGeneratorMatrixGeneratorListTemplateSpecSyncPolicyRetryBackoff? backoff,

            string? limit)
        {
            Backoff = backoff;
            Limit = limit;
        }
    }
}
