// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMergeGeneratorPluginTemplateSpecSourcePlugin
    {
        /// <summary>
        /// Environment variables passed to the plugin.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMergeGeneratorPluginTemplateSpecSourcePluginEnv> Envs;
        /// <summary>
        /// Name of the plugin. Only set the plugin name if the plugin is defined in `argocd-cm`. If the plugin is defined as a sidecar, omit the name. The plugin will be automatically matched with the Application according to the plugin's discovery rules.
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMergeGeneratorPluginTemplateSpecSourcePlugin(
            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMergeGeneratorPluginTemplateSpecSourcePluginEnv> envs,

            string? name)
        {
            Envs = envs;
            Name = name;
        }
    }
}
