// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSpecIgnoreDifference
    {
        /// <summary>
        /// The Kubernetes resource Group to match for.
        /// </summary>
        public readonly string? Group;
        /// <summary>
        /// List of JQ path expression strings targeting the field(s) to ignore.
        /// </summary>
        public readonly ImmutableArray<string> JqPathExpressions;
        /// <summary>
        /// List of JSONPaths strings targeting the field(s) to ignore.
        /// </summary>
        public readonly ImmutableArray<string> JsonPointers;
        /// <summary>
        /// The Kubernetes resource Kind to match for.
        /// </summary>
        public readonly string? Kind;
        /// <summary>
        /// List of external controller manager names whose changes to fields should be ignored.
        /// </summary>
        public readonly ImmutableArray<string> ManagedFieldsManagers;
        /// <summary>
        /// The Kubernetes resource Name to match for.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The Kubernetes resource Namespace to match for.
        /// </summary>
        public readonly string? Namespace;

        [OutputConstructor]
        private ApplicationSpecIgnoreDifference(
            string? group,

            ImmutableArray<string> jqPathExpressions,

            ImmutableArray<string> jsonPointers,

            string? kind,

            ImmutableArray<string> managedFieldsManagers,

            string? name,

            string? @namespace)
        {
            Group = group;
            JqPathExpressions = jqPathExpressions;
            JsonPointers = jsonPointers;
            Kind = kind;
            ManagedFieldsManagers = managedFieldsManagers;
            Name = name;
            Namespace = @namespace;
        }
    }
}
