// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorClusterTemplateSpecSourceKustomize
    {
        /// <summary>
        /// List of additional annotations to add to rendered manifests.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? CommonAnnotations;
        /// <summary>
        /// List of additional labels to add to rendered manifests.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? CommonLabels;
        /// <summary>
        /// List of Kustomize image override specifications.
        /// </summary>
        public readonly ImmutableArray<string> Images;
        /// <summary>
        /// Prefix appended to resources for Kustomize apps.
        /// </summary>
        public readonly string? NamePrefix;
        /// <summary>
        /// Suffix appended to resources for Kustomize apps.
        /// </summary>
        public readonly string? NameSuffix;
        /// <summary>
        /// A list of [Kustomize patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/) to apply.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorClusterTemplateSpecSourceKustomizePatch> Patches;
        /// <summary>
        /// Version of Kustomize to use for rendering manifests.
        /// </summary>
        public readonly string? Version;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorClusterTemplateSpecSourceKustomize(
            ImmutableDictionary<string, string>? commonAnnotations,

            ImmutableDictionary<string, string>? commonLabels,

            ImmutableArray<string> images,

            string? namePrefix,

            string? nameSuffix,

            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorClusterTemplateSpecSourceKustomizePatch> patches,

            string? version)
        {
            CommonAnnotations = commonAnnotations;
            CommonLabels = commonLabels;
            Images = images;
            NamePrefix = namePrefix;
            NameSuffix = nameSuffix;
            Patches = patches;
            Version = version;
        }
    }
}
