// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ClusterInfoConnectionState
    {
        /// <summary>
        /// Human readable information about the connection status.
        /// </summary>
        public readonly string? Message;
        /// <summary>
        /// Current status indicator for the connection.
        /// </summary>
        public readonly string? Status;

        [OutputConstructor]
        private ClusterInfoConnectionState(
            string? message,

            string? status)
        {
            Message = message;
            Status = status;
        }
    }
}
