// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package argocd

import (
	"context"
	"reflect"

	"errors"
	"github.com/Three141/pulumi-argocd/sdk/go/argocd/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages [clusters](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters) within ArgoCD.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Three141/pulumi-argocd/sdk/go/argocd"
//	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/eks"
//	"github.com/pulumi/pulumi-gcp/sdk/v8/go/gcp/container"
//	corev1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/core/v1"
//	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
//	rbacv1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/rbac/v1"
//	"github.com/pulumi/pulumi-std/sdk/go/std"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			invokeFile, err := std.File(ctx, &std.FileArgs{
//				Input: "path/to/ca.pem",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			// # Bearer token Authentication
//			_, err = argocd.NewCluster(ctx, "kubernetes", &argocd.ClusterArgs{
//				Server: pulumi.String("https://1.2.3.4:12345"),
//				Config: &argocd.ClusterConfigArgs{
//					BearerToken: pulumi.String("eyJhbGciOiJSUzI..."),
//					TlsClientConfig: &argocd.ClusterConfigTlsClientConfigArgs{
//						CaData: pulumi.String(invokeFile.Result),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// # GCP GKE cluster
//			cluster, err := container.LookupCluster(ctx, &container.LookupClusterArgs{
//				Name:     "cluster",
//				Location: pulumi.StringRef("europe-west1"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			argocdManager, err := corev1.NewServiceAccount(ctx, "argocd_manager", &corev1.ServiceAccountArgs{
//				Metadata: &metav1.ObjectMetaArgs{
//					Name:      pulumi.String("argocd-manager"),
//					Namespace: pulumi.String("kube-system"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			argocdManagerClusterRole, err := rbacv1.NewClusterRole(ctx, "argocd_manager", &rbacv1.ClusterRoleArgs{
//				Metadata: &metav1.ObjectMetaArgs{
//					Name: pulumi.String("argocd-manager-role"),
//				},
//				Rules: rbacv1.PolicyRuleArray{
//					&rbacv1.PolicyRuleArgs{
//						ApiGroups: pulumi.StringArray{
//							pulumi.String("*"),
//						},
//						Resources: pulumi.StringArray{
//							pulumi.String("*"),
//						},
//						Verbs: pulumi.StringArray{
//							pulumi.String("*"),
//						},
//					},
//					&rbacv1.PolicyRuleArgs{
//						NonResourceUrls: pulumi.StringArray{
//							pulumi.String("*"),
//						},
//						Verbs: pulumi.StringArray{
//							pulumi.String("*"),
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = rbacv1.NewClusterRoleBinding(ctx, "argocd_manager", &rbacv1.ClusterRoleBindingArgs{
//				Metadata: &metav1.ObjectMetaArgs{
//					Name: pulumi.String("argocd-manager-role-binding"),
//				},
//				RoleRef: &rbacv1.RoleRefArgs{
//					ApiGroup: pulumi.String("rbac.authorization.k8s.io"),
//					Kind:     pulumi.String("ClusterRole"),
//					Name: argocdManagerClusterRole.Metadata.ApplyT(func(metadata metav1.ObjectMeta) (*string, error) {
//						return &metadata.Name, nil
//					}).(pulumi.StringPtrOutput),
//				},
//				Subjects: rbacv1.SubjectArray{
//					&rbacv1.SubjectArgs{
//						Kind: pulumi.String("ServiceAccount"),
//						Name: argocdManager.Metadata.ApplyT(func(metadata metav1.ObjectMeta) (*string, error) {
//							return &metadata.Name, nil
//						}).(pulumi.StringPtrOutput),
//						Namespace: argocdManager.Metadata.ApplyT(func(metadata metav1.ObjectMeta) (*string, error) {
//							return &metadata.Namespace, nil
//						}).(pulumi.StringPtrOutput),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = corev1.NewSecret(ctx, "argocd_manager", &corev1.SecretArgs{
//				Metadata: &metav1.ObjectMetaArgs{
//					Name: argocdManager.DefaultSecretName,
//					Namespace: argocdManager.Metadata.ApplyT(func(metadata metav1.ObjectMeta) (*string, error) {
//						return &metadata.Namespace, nil
//					}).(pulumi.StringPtrOutput),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			invokeJoin1, err := std.Join(ctx, &std.JoinArgs{
//				Separator: "",
//				Input: []interface{}{
//					"https://%s",
//					cluster.Endpoint,
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			invokeBase64decode2, err := std.Base64decode(ctx, &std.Base64decodeArgs{
//				Input: cluster.MasterAuths[0].ClusterCaCertificate,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = argocd.NewCluster(ctx, "gke", &argocd.ClusterArgs{
//				Server: pulumi.String(invokeJoin1.Result),
//				Name:   pulumi.String("gke"),
//				Config: &argocd.ClusterConfigArgs{
//					BearerToken: pulumi.Any(argocdManagerKubernetesSecret.Data.Token),
//					TlsClientConfig: &argocd.ClusterConfigTlsClientConfigArgs{
//						CaData: pulumi.String(invokeBase64decode2.Result),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// # AWS EKS cluster
//			clusterGetCluster, err := eks.LookupCluster(ctx, &eks.LookupClusterArgs{
//				Name: "cluster",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			invokeJoin3, err := std.Join(ctx, &std.JoinArgs{
//				Separator: "",
//				Input: []interface{}{
//					"https://%s",
//					clusterGetCluster.Endpoint,
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			invokeBase64decode4, err := std.Base64decode(ctx, &std.Base64decodeArgs{
//				Input: clusterGetCluster.CertificateAuthorities[0].Data,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = argocd.NewCluster(ctx, "eks", &argocd.ClusterArgs{
//				Server: pulumi.String(invokeJoin3.Result),
//				Name:   pulumi.String("eks"),
//				Namespaces: pulumi.StringArray{
//					pulumi.String("default"),
//					pulumi.String("optional"),
//				},
//				Config: &argocd.ClusterConfigArgs{
//					AwsAuthConfigs: argocd.ClusterConfigAwsAuthConfigArray{
//						&argocd.ClusterConfigAwsAuthConfigArgs{
//							ClusterName: pulumi.String("myekscluster"),
//							RoleArn:     pulumi.String("arn:aws:iam::<123456789012>:role/<role-name>"),
//						},
//					},
//					TlsClientConfig: &argocd.ClusterConfigTlsClientConfigArgs{
//						CaData: pulumi.String(invokeBase64decode4.Result),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Cluster credentials can be imported using the server URL.
//
// ```sh
// $ pulumi import argocd:index/cluster:Cluster mycluster https://mycluster.io:443
// ```
type Cluster struct {
	pulumi.CustomResourceState

	// Cluster information for connecting to a cluster.
	Config ClusterConfigOutput `pulumi:"config"`
	// Information about cluster cache and state.
	Infos ClusterInfoArrayOutput `pulumi:"infos"`
	// Standard cluster secret's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadatas ClusterMetadataArrayOutput `pulumi:"metadatas"`
	// Name of the cluster. If omitted, will use the server address.
	Name pulumi.StringOutput `pulumi:"name"`
	// List of namespaces which are accessible in that cluster. Cluster level resources would be ignored if namespace list is not empty.
	Namespaces pulumi.StringArrayOutput `pulumi:"namespaces"`
	// Reference between project and cluster that allow you automatically to be added as item inside Destinations project entity. More info: https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-scoped-repositories-and-clusters.
	Project pulumi.StringPtrOutput `pulumi:"project"`
	// Server is the API server URL of the Kubernetes cluster.
	Server pulumi.StringPtrOutput `pulumi:"server"`
	// Optional shard number. Calculated on the fly by the application controller if not specified.
	Shard pulumi.StringPtrOutput `pulumi:"shard"`
}

// NewCluster registers a new resource with the given unique name, arguments, and options.
func NewCluster(ctx *pulumi.Context,
	name string, args *ClusterArgs, opts ...pulumi.ResourceOption) (*Cluster, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Config == nil {
		return nil, errors.New("invalid value for required argument 'Config'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Cluster
	err := ctx.RegisterResource("argocd:index/cluster:Cluster", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCluster gets an existing Cluster resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCluster(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ClusterState, opts ...pulumi.ResourceOption) (*Cluster, error) {
	var resource Cluster
	err := ctx.ReadResource("argocd:index/cluster:Cluster", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Cluster resources.
type clusterState struct {
	// Cluster information for connecting to a cluster.
	Config *ClusterConfig `pulumi:"config"`
	// Information about cluster cache and state.
	Infos []ClusterInfo `pulumi:"infos"`
	// Standard cluster secret's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadatas []ClusterMetadata `pulumi:"metadatas"`
	// Name of the cluster. If omitted, will use the server address.
	Name *string `pulumi:"name"`
	// List of namespaces which are accessible in that cluster. Cluster level resources would be ignored if namespace list is not empty.
	Namespaces []string `pulumi:"namespaces"`
	// Reference between project and cluster that allow you automatically to be added as item inside Destinations project entity. More info: https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-scoped-repositories-and-clusters.
	Project *string `pulumi:"project"`
	// Server is the API server URL of the Kubernetes cluster.
	Server *string `pulumi:"server"`
	// Optional shard number. Calculated on the fly by the application controller if not specified.
	Shard *string `pulumi:"shard"`
}

type ClusterState struct {
	// Cluster information for connecting to a cluster.
	Config ClusterConfigPtrInput
	// Information about cluster cache and state.
	Infos ClusterInfoArrayInput
	// Standard cluster secret's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadatas ClusterMetadataArrayInput
	// Name of the cluster. If omitted, will use the server address.
	Name pulumi.StringPtrInput
	// List of namespaces which are accessible in that cluster. Cluster level resources would be ignored if namespace list is not empty.
	Namespaces pulumi.StringArrayInput
	// Reference between project and cluster that allow you automatically to be added as item inside Destinations project entity. More info: https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-scoped-repositories-and-clusters.
	Project pulumi.StringPtrInput
	// Server is the API server URL of the Kubernetes cluster.
	Server pulumi.StringPtrInput
	// Optional shard number. Calculated on the fly by the application controller if not specified.
	Shard pulumi.StringPtrInput
}

func (ClusterState) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterState)(nil)).Elem()
}

type clusterArgs struct {
	// Cluster information for connecting to a cluster.
	Config ClusterConfig `pulumi:"config"`
	// Standard cluster secret's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadatas []ClusterMetadata `pulumi:"metadatas"`
	// Name of the cluster. If omitted, will use the server address.
	Name *string `pulumi:"name"`
	// List of namespaces which are accessible in that cluster. Cluster level resources would be ignored if namespace list is not empty.
	Namespaces []string `pulumi:"namespaces"`
	// Reference between project and cluster that allow you automatically to be added as item inside Destinations project entity. More info: https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-scoped-repositories-and-clusters.
	Project *string `pulumi:"project"`
	// Server is the API server URL of the Kubernetes cluster.
	Server *string `pulumi:"server"`
	// Optional shard number. Calculated on the fly by the application controller if not specified.
	Shard *string `pulumi:"shard"`
}

// The set of arguments for constructing a Cluster resource.
type ClusterArgs struct {
	// Cluster information for connecting to a cluster.
	Config ClusterConfigInput
	// Standard cluster secret's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadatas ClusterMetadataArrayInput
	// Name of the cluster. If omitted, will use the server address.
	Name pulumi.StringPtrInput
	// List of namespaces which are accessible in that cluster. Cluster level resources would be ignored if namespace list is not empty.
	Namespaces pulumi.StringArrayInput
	// Reference between project and cluster that allow you automatically to be added as item inside Destinations project entity. More info: https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-scoped-repositories-and-clusters.
	Project pulumi.StringPtrInput
	// Server is the API server URL of the Kubernetes cluster.
	Server pulumi.StringPtrInput
	// Optional shard number. Calculated on the fly by the application controller if not specified.
	Shard pulumi.StringPtrInput
}

func (ClusterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterArgs)(nil)).Elem()
}

type ClusterInput interface {
	pulumi.Input

	ToClusterOutput() ClusterOutput
	ToClusterOutputWithContext(ctx context.Context) ClusterOutput
}

func (*Cluster) ElementType() reflect.Type {
	return reflect.TypeOf((**Cluster)(nil)).Elem()
}

func (i *Cluster) ToClusterOutput() ClusterOutput {
	return i.ToClusterOutputWithContext(context.Background())
}

func (i *Cluster) ToClusterOutputWithContext(ctx context.Context) ClusterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterOutput)
}

// ClusterArrayInput is an input type that accepts ClusterArray and ClusterArrayOutput values.
// You can construct a concrete instance of `ClusterArrayInput` via:
//
//	ClusterArray{ ClusterArgs{...} }
type ClusterArrayInput interface {
	pulumi.Input

	ToClusterArrayOutput() ClusterArrayOutput
	ToClusterArrayOutputWithContext(context.Context) ClusterArrayOutput
}

type ClusterArray []ClusterInput

func (ClusterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Cluster)(nil)).Elem()
}

func (i ClusterArray) ToClusterArrayOutput() ClusterArrayOutput {
	return i.ToClusterArrayOutputWithContext(context.Background())
}

func (i ClusterArray) ToClusterArrayOutputWithContext(ctx context.Context) ClusterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterArrayOutput)
}

// ClusterMapInput is an input type that accepts ClusterMap and ClusterMapOutput values.
// You can construct a concrete instance of `ClusterMapInput` via:
//
//	ClusterMap{ "key": ClusterArgs{...} }
type ClusterMapInput interface {
	pulumi.Input

	ToClusterMapOutput() ClusterMapOutput
	ToClusterMapOutputWithContext(context.Context) ClusterMapOutput
}

type ClusterMap map[string]ClusterInput

func (ClusterMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Cluster)(nil)).Elem()
}

func (i ClusterMap) ToClusterMapOutput() ClusterMapOutput {
	return i.ToClusterMapOutputWithContext(context.Background())
}

func (i ClusterMap) ToClusterMapOutputWithContext(ctx context.Context) ClusterMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterMapOutput)
}

type ClusterOutput struct{ *pulumi.OutputState }

func (ClusterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Cluster)(nil)).Elem()
}

func (o ClusterOutput) ToClusterOutput() ClusterOutput {
	return o
}

func (o ClusterOutput) ToClusterOutputWithContext(ctx context.Context) ClusterOutput {
	return o
}

// Cluster information for connecting to a cluster.
func (o ClusterOutput) Config() ClusterConfigOutput {
	return o.ApplyT(func(v *Cluster) ClusterConfigOutput { return v.Config }).(ClusterConfigOutput)
}

// Information about cluster cache and state.
func (o ClusterOutput) Infos() ClusterInfoArrayOutput {
	return o.ApplyT(func(v *Cluster) ClusterInfoArrayOutput { return v.Infos }).(ClusterInfoArrayOutput)
}

// Standard cluster secret's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o ClusterOutput) Metadatas() ClusterMetadataArrayOutput {
	return o.ApplyT(func(v *Cluster) ClusterMetadataArrayOutput { return v.Metadatas }).(ClusterMetadataArrayOutput)
}

// Name of the cluster. If omitted, will use the server address.
func (o ClusterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// List of namespaces which are accessible in that cluster. Cluster level resources would be ignored if namespace list is not empty.
func (o ClusterOutput) Namespaces() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringArrayOutput { return v.Namespaces }).(pulumi.StringArrayOutput)
}

// Reference between project and cluster that allow you automatically to be added as item inside Destinations project entity. More info: https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-scoped-repositories-and-clusters.
func (o ClusterOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

// Server is the API server URL of the Kubernetes cluster.
func (o ClusterOutput) Server() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringPtrOutput { return v.Server }).(pulumi.StringPtrOutput)
}

// Optional shard number. Calculated on the fly by the application controller if not specified.
func (o ClusterOutput) Shard() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringPtrOutput { return v.Shard }).(pulumi.StringPtrOutput)
}

type ClusterArrayOutput struct{ *pulumi.OutputState }

func (ClusterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Cluster)(nil)).Elem()
}

func (o ClusterArrayOutput) ToClusterArrayOutput() ClusterArrayOutput {
	return o
}

func (o ClusterArrayOutput) ToClusterArrayOutputWithContext(ctx context.Context) ClusterArrayOutput {
	return o
}

func (o ClusterArrayOutput) Index(i pulumi.IntInput) ClusterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Cluster {
		return vs[0].([]*Cluster)[vs[1].(int)]
	}).(ClusterOutput)
}

type ClusterMapOutput struct{ *pulumi.OutputState }

func (ClusterMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Cluster)(nil)).Elem()
}

func (o ClusterMapOutput) ToClusterMapOutput() ClusterMapOutput {
	return o
}

func (o ClusterMapOutput) ToClusterMapOutputWithContext(ctx context.Context) ClusterMapOutput {
	return o
}

func (o ClusterMapOutput) MapIndex(k pulumi.StringInput) ClusterOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Cluster {
		return vs[0].(map[string]*Cluster)[vs[1].(string)]
	}).(ClusterOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterInput)(nil)).Elem(), &Cluster{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterArrayInput)(nil)).Elem(), ClusterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterMapInput)(nil)).Elem(), ClusterMap{})
	pulumi.RegisterOutputType(ClusterOutput{})
	pulumi.RegisterOutputType(ClusterArrayOutput{})
	pulumi.RegisterOutputType(ClusterMapOutput{})
}
