// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPluginTemplateSpecSourceHelmFileParameterGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the Helm parameter.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Path to the file containing the values for the Helm parameter.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        public ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPluginTemplateSpecSourceHelmFileParameterGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPluginTemplateSpecSourceHelmFileParameterGetArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPluginTemplateSpecSourceHelmFileParameterGetArgs();
    }
}
