// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorMatrixGeneratorGitDirectoryGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Flag indicating whether or not the directory should be excluded when templating.
        /// </summary>
        [Input("exclude")]
        public Input<bool>? Exclude { get; set; }

        /// <summary>
        /// Path in the repository.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        public ApplicationSetSpecGeneratorMatrixGeneratorMatrixGeneratorGitDirectoryGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMatrixGeneratorMatrixGeneratorGitDirectoryGetArgs Empty => new ApplicationSetSpecGeneratorMatrixGeneratorMatrixGeneratorGitDirectoryGetArgs();
    }
}
