// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorPluginInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("parameters", required: true)]
        private InputMap<string>? _parameters;

        /// <summary>
        /// Arbitrary key-value pairs which are passed directly as parameters to the plugin. A current limitation is that this cannot fully express the parameters that can be accepted by the plugin generator.
        /// </summary>
        public InputMap<string> Parameters
        {
            get => _parameters ?? (_parameters = new InputMap<string>());
            set => _parameters = value;
        }

        public ApplicationSetSpecGeneratorMatrixGeneratorPluginInputArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMatrixGeneratorPluginInputArgs Empty => new ApplicationSetSpecGeneratorMatrixGeneratorPluginInputArgs();
    }
}
