// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorClusterSelectorArgs : global::Pulumi.ResourceArgs
    {
        [Input("matchExpressions")]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorClusterSelectorMatchExpressionArgs>? _matchExpressions;

        /// <summary>
        /// A list of label selector requirements. The requirements are ANDed.
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorClusterSelectorMatchExpressionArgs> MatchExpressions
        {
            get => _matchExpressions ?? (_matchExpressions = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorClusterSelectorMatchExpressionArgs>());
            set => _matchExpressions = value;
        }

        [Input("matchLabels")]
        private InputMap<string>? _matchLabels;

        /// <summary>
        /// A map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of `MatchExpressions`, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
        /// </summary>
        public InputMap<string> MatchLabels
        {
            get => _matchLabels ?? (_matchLabels = new InputMap<string>());
            set => _matchLabels = value;
        }

        public ApplicationSetSpecGeneratorMergeGeneratorClusterSelectorArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorClusterSelectorArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorClusterSelectorArgs();
    }
}
