// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorMatrixGeneratorClusterTemplateSpecIgnoreDifferenceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Kubernetes resource Group to match for.
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        [Input("jqPathExpressions")]
        private InputList<string>? _jqPathExpressions;

        /// <summary>
        /// List of JQ path expression strings targeting the field(s) to ignore.
        /// </summary>
        public InputList<string> JqPathExpressions
        {
            get => _jqPathExpressions ?? (_jqPathExpressions = new InputList<string>());
            set => _jqPathExpressions = value;
        }

        [Input("jsonPointers")]
        private InputList<string>? _jsonPointers;

        /// <summary>
        /// List of JSONPaths strings targeting the field(s) to ignore.
        /// </summary>
        public InputList<string> JsonPointers
        {
            get => _jsonPointers ?? (_jsonPointers = new InputList<string>());
            set => _jsonPointers = value;
        }

        /// <summary>
        /// The Kubernetes resource Kind to match for.
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("managedFieldsManagers")]
        private InputList<string>? _managedFieldsManagers;

        /// <summary>
        /// List of external controller manager names whose changes to fields should be ignored.
        /// </summary>
        public InputList<string> ManagedFieldsManagers
        {
            get => _managedFieldsManagers ?? (_managedFieldsManagers = new InputList<string>());
            set => _managedFieldsManagers = value;
        }

        /// <summary>
        /// The Kubernetes resource Name to match for.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Kubernetes resource Namespace to match for.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        public ApplicationSetSpecGeneratorMatrixGeneratorMatrixGeneratorClusterTemplateSpecIgnoreDifferenceGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMatrixGeneratorMatrixGeneratorClusterTemplateSpecIgnoreDifferenceGetArgs Empty => new ApplicationSetSpecGeneratorMatrixGeneratorMatrixGeneratorClusterTemplateSpecIgnoreDifferenceGetArgs();
    }
}
