// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorPluginGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ConfigMap with the plugin configuration needed to retrieve the data.
        /// </summary>
        [Input("configMapRef", required: true)]
        public Input<string> ConfigMapRef { get; set; } = null!;

        /// <summary>
        /// The input parameters used for calling the plugin.
        /// </summary>
        [Input("input")]
        public Input<Inputs.ApplicationSetSpecGeneratorPluginInputGetArgs>? Input { get; set; }

        /// <summary>
        /// How often to check for changes (in seconds). Default: 3min.
        /// </summary>
        [Input("requeueAfterSeconds")]
        public Input<string>? RequeueAfterSeconds { get; set; }

        /// <summary>
        /// Generator template. Used to override the values of the spec-level template.
        /// </summary>
        [Input("template")]
        public Input<Inputs.ApplicationSetSpecGeneratorPluginTemplateGetArgs>? Template { get; set; }

        [Input("values")]
        private InputMap<string>? _values;

        /// <summary>
        /// Arbitrary string key-value pairs to pass to the template via the values field of the git generator.
        /// </summary>
        public InputMap<string> Values
        {
            get => _values ?? (_values = new InputMap<string>());
            set => _values = value;
        }

        public ApplicationSetSpecGeneratorPluginGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorPluginGetArgs Empty => new ApplicationSetSpecGeneratorPluginGetArgs();
    }
}
