// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationStatusResourceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Kubernetes resource Group.
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        [Input("healths")]
        private InputList<Inputs.ApplicationStatusResourceHealthGetArgs>? _healths;

        /// <summary>
        /// Resource health status.
        /// </summary>
        public InputList<Inputs.ApplicationStatusResourceHealthGetArgs> Healths
        {
            get => _healths ?? (_healths = new InputList<Inputs.ApplicationStatusResourceHealthGetArgs>());
            set => _healths = value;
        }

        /// <summary>
        /// Indicates whether or not this resource has a hook annotation.
        /// </summary>
        [Input("hook")]
        public Input<bool>? Hook { get; set; }

        /// <summary>
        /// The Kubernetes resource Kind.
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        /// <summary>
        /// The Kubernetes resource Name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Kubernetes resource Namespace.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// Indicates if the resources requires pruning or not.
        /// </summary>
        [Input("requiresPruning")]
        public Input<bool>? RequiresPruning { get; set; }

        /// <summary>
        /// Resource sync status.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Sync wave.
        /// </summary>
        [Input("syncWave")]
        public Input<string>? SyncWave { get; set; }

        /// <summary>
        /// The Kubernetes resource Version.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public ApplicationStatusResourceGetArgs()
        {
        }
        public static new ApplicationStatusResourceGetArgs Empty => new ApplicationStatusResourceGetArgs();
    }
}
