// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorPluginTemplateSpecSourceKustomizePatchTargetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Annotation selector to use when matching the Kubernetes resource.
        /// </summary>
        [Input("annotationSelector")]
        public Input<string>? AnnotationSelector { get; set; }

        /// <summary>
        /// The Kubernetes resource Group to match for.
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        /// <summary>
        /// The Kubernetes resource Kind to match for.
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        /// <summary>
        /// Label selector to use when matching the Kubernetes resource.
        /// </summary>
        [Input("labelSelector")]
        public Input<string>? LabelSelector { get; set; }

        /// <summary>
        /// The Kubernetes resource Name to match for.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Kubernetes resource Namespace to match for.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// The Kubernetes resource Version to match for.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public ApplicationSetSpecGeneratorPluginTemplateSpecSourceKustomizePatchTargetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorPluginTemplateSpecSourceKustomizePatchTargetArgs Empty => new ApplicationSetSpecGeneratorPluginTemplateSpecSourceKustomizePatchTargetArgs();
    }
}
