// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("directories")]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitDirectoryGetArgs>? _directories;

        /// <summary>
        /// List of directories in the source repository to use when template the Application..
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitDirectoryGetArgs> Directories
        {
            get => _directories ?? (_directories = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitDirectoryGetArgs>());
            set => _directories = value;
        }

        [Input("files")]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitFileGetArgs>? _files;

        /// <summary>
        /// List of files in the source repository to use when template the Application.
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitFileGetArgs> Files
        {
            get => _files ?? (_files = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitFileGetArgs>());
            set => _files = value;
        }

        /// <summary>
        /// Prefix for all path-related parameter names.
        /// </summary>
        [Input("pathParamPrefix")]
        public Input<string>? PathParamPrefix { get; set; }

        /// <summary>
        /// URL to the repository to use.
        /// </summary>
        [Input("repoUrl", required: true)]
        public Input<string> RepoUrl { get; set; } = null!;

        /// <summary>
        /// Revision of the source repository to use.
        /// </summary>
        [Input("revision")]
        public Input<string>? Revision { get; set; }

        /// <summary>
        /// Generator template. Used to override the values of the spec-level template.
        /// </summary>
        [Input("template")]
        public Input<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitTemplateGetArgs>? Template { get; set; }

        [Input("values")]
        private InputMap<string>? _values;

        /// <summary>
        /// Arbitrary string key-value pairs to pass to the template via the values field of the git generator.
        /// </summary>
        public InputMap<string> Values
        {
            get => _values ?? (_values = new InputMap<string>());
            set => _values = value;
        }

        public ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitGetArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitGetArgs();
    }
}
