// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorScmProviderTemplateSpecSourceHelmParameterArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines whether to tell Helm to interpret booleans and numbers as strings.
        /// </summary>
        [Input("forceString")]
        public Input<bool>? ForceString { get; set; }

        /// <summary>
        /// Name of the Helm parameter.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Value of the Helm parameter.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public ApplicationSetSpecGeneratorMatrixGeneratorScmProviderTemplateSpecSourceHelmParameterArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMatrixGeneratorScmProviderTemplateSpecSourceHelmParameterArgs Empty => new ApplicationSetSpecGeneratorMatrixGeneratorScmProviderTemplateSpecSourceHelmParameterArgs();
    }
}
