// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorScmProviderBitbucketServerBasicAuthArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Password (or personal access token) reference.
        /// </summary>
        [Input("passwordRef")]
        public Input<Inputs.ApplicationSetSpecGeneratorMatrixGeneratorScmProviderBitbucketServerBasicAuthPasswordRefArgs>? PasswordRef { get; set; }

        /// <summary>
        /// Username for Basic auth.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public ApplicationSetSpecGeneratorMatrixGeneratorScmProviderBitbucketServerBasicAuthArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMatrixGeneratorScmProviderBitbucketServerBasicAuthArgs Empty => new ApplicationSetSpecGeneratorMatrixGeneratorScmProviderBitbucketServerBasicAuthArgs();
    }
}
