// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorScmProviderGitlabTokenRefArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Key containing information in Kubernetes `Secret`.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// Name of Kubernetes `Secret`.
        /// </summary>
        [Input("secretName", required: true)]
        public Input<string> SecretName { get; set; } = null!;

        public ApplicationSetSpecGeneratorScmProviderGitlabTokenRefArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorScmProviderGitlabTokenRefArgs Empty => new ApplicationSetSpecGeneratorScmProviderGitlabTokenRefArgs();
    }
}
