// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationStatusConditionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The time the condition was last observed.
        /// </summary>
        [Input("lastTransitionTime")]
        public Input<string>? LastTransitionTime { get; set; }

        /// <summary>
        /// Human-readable message indicating details about condition.
        /// </summary>
        [Input("message")]
        public Input<string>? Message { get; set; }

        /// <summary>
        /// Application condition type.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public ApplicationStatusConditionArgs()
        {
        }
        public static new ApplicationStatusConditionArgs Empty => new ApplicationStatusConditionArgs();
    }
}
