// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPluginTemplateSpecSourceDirectoryJsonnetTlaGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines whether the variable should be evaluated as jsonnet code or treated as string.
        /// </summary>
        [Input("code")]
        public Input<bool>? Code { get; set; }

        /// <summary>
        /// Name of Jsonnet variable.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Value of Jsonnet variable.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPluginTemplateSpecSourceDirectoryJsonnetTlaGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPluginTemplateSpecSourceDirectoryJsonnetTlaGetArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPluginTemplateSpecSourceDirectoryJsonnetTlaGetArgs();
    }
}
