// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitFileGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Path to the file in the repository.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        public ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitFileGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitFileGetArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorGitFileGetArgs();
    }
}
