// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorPluginTemplateGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Kubernetes object metadata for templated Application.
        /// </summary>
        [Input("metadata")]
        public Input<Inputs.ApplicationSetSpecGeneratorMatrixGeneratorPluginTemplateMetadataGetArgs>? Metadata { get; set; }

        /// <summary>
        /// The application specification.
        /// </summary>
        [Input("spec")]
        public Input<Inputs.ApplicationSetSpecGeneratorMatrixGeneratorPluginTemplateSpecGetArgs>? Spec { get; set; }

        public ApplicationSetSpecGeneratorMatrixGeneratorPluginTemplateGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMatrixGeneratorPluginTemplateGetArgs Empty => new ApplicationSetSpecGeneratorMatrixGeneratorPluginTemplateGetArgs();
    }
}
