// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("generators", required: true)]
        private InputList<Inputs.ApplicationSetSpecGeneratorGetArgs>? _generators;

        /// <summary>
        /// Application set generators. Generators are responsible for generating parameters, which are then rendered into the template: fields of the ApplicationSet resource.
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorGetArgs> Generators
        {
            get => _generators ?? (_generators = new InputList<Inputs.ApplicationSetSpecGeneratorGetArgs>());
            set => _generators = value;
        }

        /// <summary>
        /// Enable use of [Go Text Template](https://pkg.go.dev/text/template).
        /// </summary>
        [Input("goTemplate")]
        public Input<bool>? GoTemplate { get; set; }

        [Input("goTemplateOptions")]
        private InputList<string>? _goTemplateOptions;

        /// <summary>
        /// Optional list of [Go Templating Options](https://pkg.go.dev/text/template#Template.Option). Only relevant if `GoTemplate` is true.
        /// </summary>
        public InputList<string> GoTemplateOptions
        {
            get => _goTemplateOptions ?? (_goTemplateOptions = new InputList<string>());
            set => _goTemplateOptions = value;
        }

        [Input("ignoreApplicationDifferences")]
        private InputList<Inputs.ApplicationSetSpecIgnoreApplicationDifferenceGetArgs>? _ignoreApplicationDifferences;

        /// <summary>
        /// Application Set [ignoreApplicationDifferences](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#ignore-certain-changes-to-applications).
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecIgnoreApplicationDifferenceGetArgs> IgnoreApplicationDifferences
        {
            get => _ignoreApplicationDifferences ?? (_ignoreApplicationDifferences = new InputList<Inputs.ApplicationSetSpecIgnoreApplicationDifferenceGetArgs>());
            set => _ignoreApplicationDifferences = value;
        }

        /// <summary>
        /// [Progressive Sync](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/) strategy
        /// </summary>
        [Input("strategy")]
        public Input<Inputs.ApplicationSetSpecStrategyGetArgs>? Strategy { get; set; }

        /// <summary>
        /// Application Set [sync policy](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/).
        /// </summary>
        [Input("syncPolicy")]
        public Input<Inputs.ApplicationSetSpecSyncPolicyGetArgs>? SyncPolicy { get; set; }

        /// <summary>
        /// Application set template. The template fields of the ApplicationSet spec are used to generate Argo CD Application resources.
        /// </summary>
        [Input("template", required: true)]
        public Input<Inputs.ApplicationSetSpecTemplateGetArgs> Template { get; set; } = null!;

        /// <summary>
        /// Application set template patch, as in the [Argo CD ApplicationSet spec](https://argocd-applicationset.readthedocs.io/en/stable/fields/#templatepatch).
        /// </summary>
        [Input("templatePatch")]
        public Input<string>? TemplatePatch { get; set; }

        public ApplicationSetSpecGetArgs()
        {
        }
        public static new ApplicationSetSpecGetArgs Empty => new ApplicationSetSpecGetArgs();
    }
}
