// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages ArgoCD [account](https://argo-cd.readthedocs.io/en/latest/user-guide/commands/argocd_account/) JWT tokens.
 *
 * > **Security Notice** The JWT token generated by this resource is treated as sensitive and, thus, not displayed in console output. However, it will be stored *unencrypted* in your Pulumi state file. Read more about sensitive data handling in the Pulumi documentation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as argocd from "@three14/pulumi-argocd";
 *
 * // Token for account configured on the `provider`
 * const _this = new argocd.AccountToken("this", {renewAfter: "168h"});
 * // Token for ac count `foo`
 * const foo = new argocd.AccountToken("foo", {
 *     account: "foo",
 *     expiresIn: "168h",
 *     renewBefore: "84h",
 * });
 * ```
 */
export class AccountToken extends pulumi.CustomResource {
    /**
     * Get an existing AccountToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AccountTokenState, opts?: pulumi.CustomResourceOptions): AccountToken {
        return new AccountToken(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'argocd:index/accountToken:AccountToken';

    /**
     * Returns true if the given object is an instance of AccountToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AccountToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AccountToken.__pulumiType;
    }

    /**
     * Account name. Defaults to the current account. I.e. the account configured on the `provider` block.
     */
    declare public readonly account: pulumi.Output<string | undefined>;
    /**
     * If `expiresIn` is set, Unix timestamp upon which the token will expire.
     */
    declare public /*out*/ readonly expiresAt: pulumi.Output<string>;
    /**
     * Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `12h`, `7d`. Default: No expiration.
     */
    declare public readonly expiresIn: pulumi.Output<string | undefined>;
    /**
     * Unix timestamp at which the token was issued.
     */
    declare public /*out*/ readonly issuedAt: pulumi.Output<string>;
    /**
     * The raw JWT.
     */
    declare public /*out*/ readonly jwt: pulumi.Output<string>;
    /**
     * Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renewAfter`. I.e. if `currentDate - issuedAt > renewAfter`.
     */
    declare public readonly renewAfter: pulumi.Output<string | undefined>;
    /**
     * Duration to control token silent regeneration based on remaining token lifetime. If `expiresIn` is set, Pulumi will regenerate the token if `expiresAt - currentDate < renewBefore`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
     */
    declare public readonly renewBefore: pulumi.Output<string | undefined>;

    /**
     * Create a AccountToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AccountTokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccountTokenArgs | AccountTokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AccountTokenState | undefined;
            resourceInputs["account"] = state?.account;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["expiresIn"] = state?.expiresIn;
            resourceInputs["issuedAt"] = state?.issuedAt;
            resourceInputs["jwt"] = state?.jwt;
            resourceInputs["renewAfter"] = state?.renewAfter;
            resourceInputs["renewBefore"] = state?.renewBefore;
        } else {
            const args = argsOrState as AccountTokenArgs | undefined;
            resourceInputs["account"] = args?.account;
            resourceInputs["expiresIn"] = args?.expiresIn;
            resourceInputs["renewAfter"] = args?.renewAfter;
            resourceInputs["renewBefore"] = args?.renewBefore;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["issuedAt"] = undefined /*out*/;
            resourceInputs["jwt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["jwt"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(AccountToken.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AccountToken resources.
 */
export interface AccountTokenState {
    /**
     * Account name. Defaults to the current account. I.e. the account configured on the `provider` block.
     */
    account?: pulumi.Input<string>;
    /**
     * If `expiresIn` is set, Unix timestamp upon which the token will expire.
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `12h`, `7d`. Default: No expiration.
     */
    expiresIn?: pulumi.Input<string>;
    /**
     * Unix timestamp at which the token was issued.
     */
    issuedAt?: pulumi.Input<string>;
    /**
     * The raw JWT.
     */
    jwt?: pulumi.Input<string>;
    /**
     * Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renewAfter`. I.e. if `currentDate - issuedAt > renewAfter`.
     */
    renewAfter?: pulumi.Input<string>;
    /**
     * Duration to control token silent regeneration based on remaining token lifetime. If `expiresIn` is set, Pulumi will regenerate the token if `expiresAt - currentDate < renewBefore`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
     */
    renewBefore?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AccountToken resource.
 */
export interface AccountTokenArgs {
    /**
     * Account name. Defaults to the current account. I.e. the account configured on the `provider` block.
     */
    account?: pulumi.Input<string>;
    /**
     * Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `12h`, `7d`. Default: No expiration.
     */
    expiresIn?: pulumi.Input<string>;
    /**
     * Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renewAfter`. I.e. if `currentDate - issuedAt > renewAfter`.
     */
    renewAfter?: pulumi.Input<string>;
    /**
     * Duration to control token silent regeneration based on remaining token lifetime. If `expiresIn` is set, Pulumi will regenerate the token if `expiresAt - currentDate < renewBefore`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
     */
    renewBefore?: pulumi.Input<string>;
}
