// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages [applications](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#applications) within ArgoCD.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as argocd from "@three14/pulumi-argocd";
 *
 * // Kustomize application
 * const kustomize = new argocd.Application("kustomize", {
 *     metadata: {
 *         name: "kustomize-app",
 *         namespace: "argocd",
 *         labels: {
 *             test: "true",
 *         },
 *     },
 *     cascade: false,
 *     wait: true,
 *     spec: {
 *         project: "myproject",
 *         destination: {
 *             server: "https://kubernetes.default.svc",
 *             namespace: "foo",
 *         },
 *         sources: [{
 *             repoUrl: "https://github.com/kubernetes-sigs/kustomize",
 *             path: "examples/helloWorld",
 *             targetRevision: "master",
 *             kustomize: {
 *                 namePrefix: "foo-",
 *                 nameSuffix: "-bar",
 *                 images: ["hashicorp/terraform:light"],
 *                 commonLabels: {
 *                     "this.is.a.common": "la-bel",
 *                     "another.io/one": "true",
 *                 },
 *             },
 *         }],
 *         syncPolicy: {
 *             automated: {
 *                 prune: true,
 *                 selfHeal: true,
 *                 allowEmpty: true,
 *             },
 *             syncOptions: ["Validate=false"],
 *             retry: {
 *                 limit: "5",
 *                 backoff: {
 *                     duration: "30s",
 *                     maxDuration: "2m",
 *                     factor: "2",
 *                 },
 *             },
 *         },
 *         ignoreDifferences: [
 *             {
 *                 group: "apps",
 *                 kind: "Deployment",
 *                 jsonPointers: ["/spec/replicas"],
 *             },
 *             {
 *                 group: "apps",
 *                 kind: "StatefulSet",
 *                 name: "someStatefulSet",
 *                 jsonPointers: [
 *                     "/spec/replicas",
 *                     "/spec/template/spec/metadata/labels/bar",
 *                 ],
 *                 jqPathExpressions: [
 *                     ".spec.replicas",
 *                     ".spec.template.spec.metadata.labels.bar",
 *                 ],
 *             },
 *         ],
 *     },
 * });
 * // Helm application
 * const helm = new argocd.Application("helm", {
 *     metadata: {
 *         name: "helm-app",
 *         namespace: "argocd",
 *         labels: {
 *             test: "true",
 *         },
 *     },
 *     spec: {
 *         destination: {
 *             server: "https://kubernetes.default.svc",
 *             namespace: "default",
 *         },
 *         sources: [{
 *             repoUrl: "https://some.chart.repo.io",
 *             chart: "mychart",
 *             targetRevision: "1.2.3",
 *             helm: {
 *                 releaseName: "testing",
 *                 parameters: [
 *                     {
 *                         name: "image.tag",
 *                         value: "1.2.3",
 *                     },
 *                     {
 *                         name: "someotherparameter",
 *                         value: "true",
 *                     },
 *                 ],
 *                 valueFiles: ["values-test.yml"],
 *                 values: JSON.stringify({
 *                     someparameter: {
 *                         enabled: true,
 *                         someArray: [
 *                             "foo",
 *                             "bar",
 *                         ],
 *                     },
 *                 }),
 *             },
 *         }],
 *     },
 * });
 * // Multiple Application Sources with Helm value files from external Git repository
 * const multipleSources = new argocd.Application("multiple_sources", {
 *     metadata: {
 *         name: "helm-app-with-external-values",
 *         namespace: "argocd",
 *     },
 *     spec: {
 *         project: "default",
 *         sources: [
 *             {
 *                 repoUrl: "https://charts.helm.sh/stable",
 *                 chart: "wordpress",
 *                 targetRevision: "9.0.3",
 *                 helm: {
 *                     valueFiles: ["$values/helm-dependency/values.yaml"],
 *                 },
 *             },
 *             {
 *                 repoUrl: "https://github.com/argoproj/argocd-example-apps.git",
 *                 targetRevision: "HEAD",
 *                 ref: "values",
 *             },
 *         ],
 *         destination: {
 *             server: "https://kubernetes.default.svc",
 *             namespace: "default",
 *         },
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * ArgoCD applications can be imported using an id consisting of `{name}:{namespace}`.
 *
 * ```sh
 * $ pulumi import argocd:index/application:Application myapp myapp:argocd
 * ```
 */
export class Application extends pulumi.CustomResource {
    /**
     * Get an existing Application resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApplicationState, opts?: pulumi.CustomResourceOptions): Application {
        return new Application(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'argocd:index/application:Application';

    /**
     * Returns true if the given object is an instance of Application.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Application {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Application.__pulumiType;
    }

    /**
     * Whether to applying cascading deletion when application is removed.
     */
    declare public readonly cascade: pulumi.Output<boolean | undefined>;
    /**
     * Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
     */
    declare public readonly metadata: pulumi.Output<outputs.ApplicationMetadata>;
    /**
     * The application specification.
     */
    declare public readonly spec: pulumi.Output<outputs.ApplicationSpec>;
    /**
     * Status information for the application. **Note**: this is not guaranteed to be up to date immediately after creating/updating an application unless `wait=true`.
     */
    declare public /*out*/ readonly statuses: pulumi.Output<outputs.ApplicationStatus[]>;
    /**
     * Whether to validate the application spec before creating or updating the application.
     */
    declare public readonly validate: pulumi.Output<boolean | undefined>;
    /**
     * Upon application creation or update, wait for application health/sync status to be healthy/Synced, upon application deletion, wait for application to be removed, when set to true. Wait timeouts are controlled by the provider Create, Update and Delete resource timeouts (all default to 5 minutes). **Note**: if ArgoCD decides not to sync an application (e.g. because the project to which the application belongs has a `syncWindow` applied) then you will experience an expected timeout event if `wait = true`.
     */
    declare public readonly wait: pulumi.Output<boolean | undefined>;

    /**
     * Create a Application resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApplicationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApplicationArgs | ApplicationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApplicationState | undefined;
            resourceInputs["cascade"] = state?.cascade;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["spec"] = state?.spec;
            resourceInputs["statuses"] = state?.statuses;
            resourceInputs["validate"] = state?.validate;
            resourceInputs["wait"] = state?.wait;
        } else {
            const args = argsOrState as ApplicationArgs | undefined;
            if (args?.metadata === undefined && !opts.urn) {
                throw new Error("Missing required property 'metadata'");
            }
            if (args?.spec === undefined && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            resourceInputs["cascade"] = args?.cascade;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["spec"] = args?.spec;
            resourceInputs["validate"] = args?.validate;
            resourceInputs["wait"] = args?.wait;
            resourceInputs["statuses"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Application.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Application resources.
 */
export interface ApplicationState {
    /**
     * Whether to applying cascading deletion when application is removed.
     */
    cascade?: pulumi.Input<boolean>;
    /**
     * Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
     */
    metadata?: pulumi.Input<inputs.ApplicationMetadata>;
    /**
     * The application specification.
     */
    spec?: pulumi.Input<inputs.ApplicationSpec>;
    /**
     * Status information for the application. **Note**: this is not guaranteed to be up to date immediately after creating/updating an application unless `wait=true`.
     */
    statuses?: pulumi.Input<pulumi.Input<inputs.ApplicationStatus>[]>;
    /**
     * Whether to validate the application spec before creating or updating the application.
     */
    validate?: pulumi.Input<boolean>;
    /**
     * Upon application creation or update, wait for application health/sync status to be healthy/Synced, upon application deletion, wait for application to be removed, when set to true. Wait timeouts are controlled by the provider Create, Update and Delete resource timeouts (all default to 5 minutes). **Note**: if ArgoCD decides not to sync an application (e.g. because the project to which the application belongs has a `syncWindow` applied) then you will experience an expected timeout event if `wait = true`.
     */
    wait?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Application resource.
 */
export interface ApplicationArgs {
    /**
     * Whether to applying cascading deletion when application is removed.
     */
    cascade?: pulumi.Input<boolean>;
    /**
     * Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
     */
    metadata: pulumi.Input<inputs.ApplicationMetadata>;
    /**
     * The application specification.
     */
    spec: pulumi.Input<inputs.ApplicationSpec>;
    /**
     * Whether to validate the application spec before creating or updating the application.
     */
    validate?: pulumi.Input<boolean>;
    /**
     * Upon application creation or update, wait for application health/sync status to be healthy/Synced, upon application deletion, wait for application to be removed, when set to true. Wait timeouts are controlled by the provider Create, Update and Delete resource timeouts (all default to 5 minutes). **Note**: if ArgoCD decides not to sync an application (e.g. because the project to which the application belongs has a `syncWindow` applied) then you will experience an expected timeout event if `wait = true`.
     */
    wait?: pulumi.Input<boolean>;
}
