// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AccountTokenArgs, AccountTokenState } from "./accountToken";
export type AccountToken = import("./accountToken").AccountToken;
export const AccountToken: typeof import("./accountToken").AccountToken = null as any;
utilities.lazyLoad(exports, ["AccountToken"], () => require("./accountToken"));

export { ApplicationArgs, ApplicationState } from "./application";
export type Application = import("./application").Application;
export const Application: typeof import("./application").Application = null as any;
utilities.lazyLoad(exports, ["Application"], () => require("./application"));

export { ApplicationSetArgs, ApplicationSetState } from "./applicationSet";
export type ApplicationSet = import("./applicationSet").ApplicationSet;
export const ApplicationSet: typeof import("./applicationSet").ApplicationSet = null as any;
utilities.lazyLoad(exports, ["ApplicationSet"], () => require("./applicationSet"));

export { ClusterArgs, ClusterState } from "./cluster";
export type Cluster = import("./cluster").Cluster;
export const Cluster: typeof import("./cluster").Cluster = null as any;
utilities.lazyLoad(exports, ["Cluster"], () => require("./cluster"));

export * from "./provider";
import { Provider } from "./provider";


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "argocd:index/accountToken:AccountToken":
                return new AccountToken(name, <any>undefined, { urn })
            case "argocd:index/application:Application":
                return new Application(name, <any>undefined, { urn })
            case "argocd:index/applicationSet:ApplicationSet":
                return new ApplicationSet(name, <any>undefined, { urn })
            case "argocd:index/cluster:Cluster":
                return new Cluster(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("argocd", "index/accountToken", _module)
pulumi.runtime.registerResourceModule("argocd", "index/application", _module)
pulumi.runtime.registerResourceModule("argocd", "index/applicationSet", _module)
pulumi.runtime.registerResourceModule("argocd", "index/cluster", _module)
pulumi.runtime.registerResourcePackage("argocd", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:argocd") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
